name: vicky
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyspark
  - pandas
  - numpy
  - pyarrow
  - sqlalchemy
  - psycopg2-binary
  - streamlit
  - scikit-learn
  - great-expectations
  - matplotlib
  - plotly
  - jupyter
  - python-dotenv
  - postgresql=16
